version: '3.7'
services:
  database:
    image: postgres
    container_name: db_futAPI
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mateus
      - POSTGRES_PASSWORD=1212
      - POSTGRES_DB=futAPI
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  app:
    build: .
    depends_on:
      - database
    container_name: futAPI
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
